import { Geist, Geist_Mono } from "next/font/google";
import NextAuthProvider from "@/components/session_provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "PFVI System",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextAuthProvider session={session}>
          {children}
          <Toaster
            position="top-center"
            reverseOrder={false}
            toastOptions={{
              className: "text-sm font-medium",
              style: {
                background: "#fff",
                color: "#333",
                border: "1px solid #e5e7eb",
              },
              success: {
                iconTheme: {
                  primary: "#4ade80",
                  secondary: "#ecfdf5",
                },
              },
              error: {
                iconTheme: {
                  primary: "#f87171",
                  secondary: "#fef2f2",
                },
              },
            }}
          />
        </NextAuthProvider>
      </body>
    </html>
  );
}